builders:
  routeable:
    import: "package:strong_router/builder.dart"
    builder_factories: ["routeable"]
    build_extensions: { ".dart": ["routeable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
