name: strong_router
description: A strongly typed router.
version: 1.1.0
homepage: https://github.com/lowski/strong_router

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^5.2.0
  flutter:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.2.6
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
